#:project ../src/DiffView.Avalonia/DiffView.Avalonia.csproj

// scripts/gen-locale-review.cs — a .NET 10 file-based app.
//
// Writes docs/locale-review/<culture>.md, the document a native speaker reviews a shipped locale
// from. The eight locales are machine-generated and unread; the parity gate proves every key is
// present and every placeholder preserved and proves nothing about whether the wording is right,
// and a reviewer cannot judge wording from 143 <data> elements in XML. Run from the repository
// root; the .sh and .ps1 wrappers beside this file do that for you.
//
//   dotnet run scripts/gen-locale-review.cs                  rewrite every locale's document
//   dotnet run scripts/gen-locale-review.cs -- de-DE         just the one
//   dotnet run scripts/gen-locale-review.cs -- --check       report only; exit 1 if a committed file differs
//
// GENERATED AND GATED, NEVER EDITED. A correction goes into the .resx and this regenerates — the
// same contract gen-strings.cs has with the neutral resx. A document that is also an input cannot
// be drift-gated, and the moment it is edited the repository has two spellings of German and no
// rule about which one wins.

using System.Globalization;
using System.Text;
using System.Xml.Linq;
using Bennewitz.Ninja.DiffView.Avalonia;

const string LocaleDirectory = "src/DiffView.Avalonia/Localization";
const string OutputDirectory = "docs/locale-review";
const string DocumentationFile = "DiffView.Avalonia.xml";

string[] arguments = args;
bool check = arguments.Contains("--check");
string[] wanted = arguments.Where(a => !a.StartsWith("--", StringComparison.Ordinal)).ToArray();

if (!Directory.Exists(LocaleDirectory))
{
    Fail($"'{LocaleDirectory}' not found — run this from the repository root, or use the wrappers beside it.");
}

IReadOnlyDictionary<string, string> summaries = Summaries();
IReadOnlyDictionary<string, string> english = DiffViewStrings.EnglishDefaults;

string[] cultures = Directory.GetFiles(LocaleDirectory, "Strings.*.resx")
    .Select(path => Path.GetFileNameWithoutExtension(path)["Strings.".Length..])
    .Where(culture => wanted.Length == 0 || wanted.Contains(culture, StringComparer.OrdinalIgnoreCase))
    .OrderBy(culture => culture, StringComparer.Ordinal)
    .ToArray();

if (cultures.Length == 0)
{
    Fail(wanted.Length == 0
        ? $"No 'Strings.<culture>.resx' under '{LocaleDirectory}'."
        : $"No locale matched {string.Join(", ", wanted)}.");
}

Directory.CreateDirectory(OutputDirectory);
List<string> stale = [];

foreach (string culture in cultures)
{
    string rendered = Render(culture);
    string target = Path.Combine(OutputDirectory, culture + ".md");

    if (check)
    {
        string committed = File.Exists(target) ? File.ReadAllText(target) : string.Empty;
        if (!string.Equals(committed, rendered, StringComparison.Ordinal))
        {
            stale.Add(target);
        }

        continue;
    }

    File.WriteAllText(target, rendered);
    Console.WriteLine($"wrote {target}");
}

if (check)
{
    if (stale.Count > 0)
    {
        Console.Error.WriteLine("These review documents no longer match the strings they describe:");
        stale.ForEach(path => Console.Error.WriteLine("  " + path));
        Console.Error.WriteLine("Run: dotnet run scripts/gen-locale-review.cs");
        return 1;
    }

    Console.WriteLine($"{cultures.Length} review document(s) match their locale.");
}

return 0;

// The whole document for one culture. Keys are ordered by name, which groups them by the surface
// they belong to — every Header.* together, every Menu.* together — so a reviewer reads one part
// of the interface at a time rather than jumping around it.
string Render(string culture)
{
    IReadOnlyDictionary<string, string> translated = ReadResx(Path.Combine(LocaleDirectory, $"Strings.{culture}.resx"), culture);
    CultureInfo info = CultureInfo.GetCultureInfo(culture);

    StringBuilder text = new();
    text.AppendLine($"# Locale review — {culture} ({info.EnglishName})");
    text.AppendLine();
    text.AppendLine("**Generated by `scripts/gen-locale-review.cs`. Do not edit this file.** A correction belongs in");
    text.AppendLine($"`{LocaleDirectory}/Strings.{culture}.resx`, against the key in the first column; this document is");
    text.AppendLine("regenerated from it and a test fails if the two drift apart.");
    text.AppendLine();
    text.AppendLine($"These {translated.Count} strings were **machine-translated and have not been read by a speaker of");
    text.AppendLine($"{info.EnglishName}**. That is what this document exists to change. What is already guaranteed is");
    text.AppendLine("structural — every key present, every placeholder preserved — and none of it is about whether the");
    text.AppendLine("wording is right, natural, or the register a developer tool should use.");
    text.AppendLine();
    text.AppendLine("Two things worth knowing before reading:");
    text.AppendLine();
    text.AppendLine("- **A placeholder must survive.** `{0}` and its siblings are replaced at runtime. They may be");
    text.AppendLine("  reordered to suit the language, and they may not be dropped, renumbered or invented. The");
    text.AppendLine("  *Holds* column says what each one will contain.");
    text.AppendLine("- **A string that names a side is a whole sentence per direction**, never one sentence with the");
    text.AppendLine("  word *left* or *right* pasted in, because a pasted word cannot be inflected. If a translation");
    text.AppendLine("  reads as though a word was dropped into it, that is the defect to report.");
    text.AppendLine();
    text.AppendLine($"To see a string in place: `dotnet run --project src/DiffView.Demo -- --culture {culture}`.");
    text.AppendLine();
    text.AppendLine("| Key | What it is | Holds | English | " + culture + " |");
    text.AppendLine("|---|---|---|---|---|");

    foreach (string key in english.Keys.OrderBy(k => k, StringComparer.Ordinal))
    {
        if (!translated.TryGetValue(key, out string? value))
        {
            Fail($"{culture}: '{key}' has no translation. The parity gate should have caught this first.");
        }

        string summary = summaries.TryGetValue(key, out string? found) ? found : string.Empty;
        if (summary.Length == 0)
        {
            Fail($"{culture}: '{key}' has no <summary>, so its row would carry no context at all.");
        }

        text.Append("| `").Append(key).Append("` | ")
            .Append(Cell(summary, key, culture)).Append(" | ")
            .Append(Holds(english[key])).Append(" | ")
            .Append(Cell(english[key], key, culture)).Append(" | ")
            .Append(Cell(value!, key, culture)).AppendLine(" |");
    }

    return text.ToString();
}

// A cell that cannot break the table. A pipe is escaped; a newline cannot be, and a row silently
// split in two is a defect nobody notices in a 143-row document, so it fails by name instead.
// No shipped string contains either today — which is exactly when to decide what happens when one
// does.
string Cell(string value, string key, string culture)
{
    if (value.Contains('\n') || value.Contains('\r'))
    {
        Fail($"{culture}: '{key}' contains a line break, which no markdown table cell can hold. "
             + "Either the string is wrong or this generator needs a different layout.");
    }

    return value.Replace("|", "\\|", StringComparison.Ordinal);
}

// The placeholder indices the string actually takes, read off the string rather than off its
// summary, so the two columns disagree visibly if they ever disagree at all.
string Holds(string value)
{
    List<int> indices = [];
    for (int i = 0; i < value.Length; i++)
    {
        if (value[i] == '{' && i + 1 < value.Length && value[i + 1] == '{')
        {
            i++;
            continue;
        }

        if (value[i] != '{')
        {
            continue;
        }

        int end = value.IndexOf('}', i);
        if (end < 0)
        {
            continue;
        }

        string inner = value[(i + 1)..end];
        int comma = inner.IndexOfAny([',', ':']);
        if (int.TryParse(comma < 0 ? inner : inner[..comma], out int index) && !indices.Contains(index))
        {
            indices.Add(index);
        }

        i = end;
    }

    return indices.Count == 0 ? "—" : string.Join(" ", indices.Order().Select(i => $"`{{{i}}}`"));
}

IReadOnlyDictionary<string, string> ReadResx(string path, string culture)
{
    if (!File.Exists(path))
    {
        Fail($"{culture}: '{path}' not found.");
    }

    Dictionary<string, string> values = new(StringComparer.Ordinal);
    foreach (XElement data in XDocument.Load(path).Root!.Elements("data"))
    {
        string? name = data.Attribute("name")?.Value;
        if (name is not null)
        {
            values[name] = data.Element("value")?.Value ?? string.Empty;
        }
    }

    return values;
}

// The <summary> per key, from the XML documentation build output rather than from the source file:
// this is the same artifact StringCatalogueTests gates, so what a reviewer reads and what the test
// checks cannot be two different things. Absence is fatal — a document whose context column is
// silently empty looks complete and is not.
IReadOnlyDictionary<string, string> Summaries()
{
    string? path = new[]
        {
            Path.Combine(AppContext.BaseDirectory, DocumentationFile),
            Path.Combine("src/DiffView.Avalonia/bin/Debug/net10.0", DocumentationFile),
            Path.Combine("src/DiffView.Avalonia/bin/Release/net10.0", DocumentationFile),
        }
        .FirstOrDefault(File.Exists);

    if (path is null)
    {
        Fail($"'{DocumentationFile}' not found. GenerateDocumentationFile is true in "
             + "DiffView.Avalonia.csproj, so a build of that project produces it; build first.");
    }

    const string Prefix = "F:Bennewitz.Ninja.DiffView.Avalonia.DiffViewStrings.";

    // The field name the documentation is keyed by is the constant's name; the review is keyed by
    // the string it holds. Reflection over the same constants bridges the two.
    Dictionary<string, string> byField = new(StringComparer.Ordinal);
    foreach (XElement member in XDocument.Load(path!).Descendants("member"))
    {
        string? id = member.Attribute("name")?.Value;
        XElement? summary = member.Element("summary");
        if (id is not null && summary is not null && id.StartsWith(Prefix, StringComparison.Ordinal))
        {
            byField[id[Prefix.Length..]] = Collapse(summary.Value);
        }
    }

    Dictionary<string, string> byKey = new(StringComparer.Ordinal);
    foreach (System.Reflection.FieldInfo field in typeof(DiffViewStrings).GetFields())
    {
        if (field is { IsLiteral: true, IsInitOnly: false }
            && field.FieldType == typeof(string)
            && field.GetRawConstantValue() is string key
            && byField.TryGetValue(field.Name, out string? summary))
        {
            byKey[key] = summary;
        }
    }

    return byKey;
}

static string Collapse(string text)
{
    return string.Join(' ', text.Split((char[])['\n', '\r', '\t', ' '], StringSplitOptions.RemoveEmptyEntries));
}

static void Fail(string message)
{
    Console.Error.WriteLine(message);
    Environment.Exit(1);
}
