#:project ../src/DiffView.Avalonia/DiffView.Avalonia.csproj

// scripts/gen-strings.cs — a .NET 10 file-based app.
//
// Writes src/DiffView.Avalonia/Localization/Strings.resx from DiffViewStrings.EnglishDefaults, so
// the neutral resource the satellite assemblies hang off is generated rather than authored and
// cannot drift from the compiled table behind it. Run from the repository root; the .sh and .ps1
// wrappers beside this file do that for you.
//
//   dotnet run scripts/gen-strings.cs                 rewrite the neutral resx
//   dotnet run scripts/gen-strings.cs -- --check      report only; exit 1 if the committed file differs
//
// The locale files beside it — Strings.de-DE.resx and the rest — are translations and are never
// touched here. Only the neutral English one is generated.

using System.Xml.Linq;
using Bennewitz.Ninja.DiffView;

const string Target = "src/DiffView.Avalonia/Localization/Strings.resx";

// The schema block every .resx carries, verbatim, so the file validates in tooling that checks it.
// Parsed rather than built element by element: the xsd prefix has to survive into the attribute
// values (type="xsd:string"), which a constructed tree does not guarantee.
const string Preamble = """
    <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
      <xsd:element name="root" msdata:IsDataSet="true">
        <xsd:complexType>
          <xsd:choice maxOccurs="unbounded">
            <xsd:element name="data">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                </xsd:sequence>
                <xsd:attribute name="name" type="xsd:string" use="required" />
                <xsd:attribute name="xml:space" type="xsd:string" />
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="resheader">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="value" type="xsd:string" minOccurs="0" />
                </xsd:sequence>
                <xsd:attribute name="name" type="xsd:string" use="required" />
              </xsd:complexType>
            </xsd:element>
          </xsd:choice>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
    """;

bool check = args.Contains("--check", StringComparer.Ordinal);

if (!File.Exists("DiffView.slnx"))
{
    Console.Error.WriteLine("gen-strings: run me from the repository root.");
    return 2;
}

string generated = Build(DiffViewStrings.EnglishDefaults, Preamble);

if (check)
{
    if (!File.Exists(Target))
    {
        Console.Error.WriteLine($"gen-strings: {Target} does not exist. Run: dotnet run scripts/gen-strings.cs");
        return 1;
    }

    if (!string.Equals(Normalise(File.ReadAllText(Target)), Normalise(generated), StringComparison.Ordinal))
    {
        Console.Error.WriteLine($"gen-strings: {Target} is stale. Run: dotnet run scripts/gen-strings.cs");
        return 1;
    }

    Console.WriteLine($"gen-strings: {Target} is current ({DiffViewStrings.EnglishDefaults.Count} entries).");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(Target)!);
File.WriteAllText(Target, generated);
Console.WriteLine($"gen-strings: wrote {Target} ({DiffViewStrings.EnglishDefaults.Count} entries).");
return 0;

// Line endings are normalised before comparing, so a checkout under core.autocrlf does not read as
// drift; the file itself is written with the platform's, as every other generated file here is.
static string Normalise(string text)
{
    return text.Replace("\r\n", "\n", StringComparison.Ordinal);
}

static string Build(IReadOnlyDictionary<string, string> entries, string preamble)
{
    XNamespace xml = "http://www.w3.org/XML/1998/namespace";
    XElement root = new(
        "root",
        new XComment(
            " Generated by scripts/gen-strings.cs from DiffViewStrings.EnglishDefaults. Do not edit: " +
            "the English text is authored in DiffViewStrings and a drift test holds this file to it. " +
            "The locale files beside it are translations and are authored. "),
        XElement.Parse(preamble),
        Header("resmimetype", "text/microsoft-resx"),
        Header("version", "2.0"),
        Header("reader", "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
        Header("writer", "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"));

    foreach (KeyValuePair<string, string> entry in entries.OrderBy(e => e.Key, StringComparer.Ordinal))
    {
        root.Add(new XElement(
            "data",
            new XAttribute("name", entry.Key),
            new XAttribute(xml + "space", "preserve"),
            new XElement("value", entry.Value)));
    }

    XDocument document = new(new XDeclaration("1.0", "utf-8", null), root);
    return document.Declaration + Environment.NewLine + document.ToString() + Environment.NewLine;
}

static XElement Header(string name, string value)
{
    return new XElement("resheader", new XAttribute("name", name), new XElement("value", value));
}
