namespace Bennewitz.Ninja.DiffView;

/// <summary>
/// Locations of the resources a host includes to style the DiffView controls.
/// </summary>
public static class DiffViewResources
{
    /// <summary>
    /// The one style include every host adds:
    /// <c>&lt;StyleInclude Source="avares://DiffView.Avalonia/Themes/DiffView.axaml" /&gt;</c>.
    /// It defines every <c>DiffView.*</c> token the controls use, for every theme variant, and
    /// never references a host theme's own keys.
    /// </summary>
    public static Uri ThemeUri { get; } = new("avares://DiffView.Avalonia/Themes/DiffView.axaml");

    /// <summary>
    /// The default <c>DiffView.*</c> palette on its own, as a resource dictionary — what
    /// <see cref="ThemeUri"/> merges. A host that wants only the tokens (its own styles, DiffView's
    /// colours) merges this instead.
    /// </summary>
    public static Uri TokensUri { get; } = new("avares://DiffView.Avalonia/Themes/DiffView.Tokens.axaml");

    /// <summary>
    /// The colour-blind-safe palette: the same keys on blue / vermillion / purple for inserted /
    /// deleted / modified. Merge it after <see cref="ThemeUri"/> to replace the default palette.
    /// </summary>
    public static Uri ColorBlindTokensUri { get; } = new("avares://DiffView.Avalonia/Themes/DiffView.Tokens.ColorBlind.axaml");

    /// <summary>
    /// The control themes of <see cref="DiffPanePresenter"/> and its text area. The presenter
    /// merges their compiled form, <see cref="DiffPanePresenterTheme"/>, into its own resources,
    /// so a host never includes this; the URI is here for a host that wants to derive its own
    /// theme from it in XAML.
    /// </summary>
    public static Uri PresenterThemeUri { get; } = new("avares://DiffView.Avalonia/Themes/DiffPanePresenter.axaml");

    /// <summary>
    /// The control themes of <see cref="SideBySideDiffView"/>, <see cref="DiffPaneHeader"/> and
    /// <see cref="DiffStatusStrip"/>; their compiled form, <see cref="SideBySideDiffViewTheme"/>,
    /// travels with the controls the same way.
    /// </summary>
    public static Uri CompositeThemeUri { get; } = new("avares://DiffView.Avalonia/Themes/SideBySideDiffView.axaml");

    /// <summary>
    /// The resource key of the panes' monospace font family, defined by <see cref="ThemeUri"/>
    /// as <c>Cascadia Mono, Consolas, Menlo, DejaVu Sans Mono, monospace</c>. A host overrides
    /// the font by defining the same key in its own resources.
    /// </summary>
    public const string MonospaceFontFamilyKey = "DiffView.MonospaceFontFamily";

    /// <summary>
    /// Every Fluent-family key Semi leaves undefined, mapped onto Semi's own tokens — generated by
    /// <c>theme-audit compat</c>. A host running Semi merges it after the theme when it also hosts
    /// controls templated for Fluent (AvaloniaEdit's search panel among them), so they stop going
    /// invisible. Not needed for DiffView's own controls.
    /// </summary>
    public static Uri FluentCompatUri { get; } = new("avares://DiffView.Avalonia/Themes/Compat/FluentKeys.Semi.axaml");

    /// <summary>The Simple-theme sibling of <see cref="FluentCompatUri"/>.</summary>
    public static Uri SimpleCompatUri { get; } = new("avares://DiffView.Avalonia/Themes/Compat/SimpleKeys.Semi.axaml");
}
